[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "~1.3.1"

[[override]]
  name = "github.com/docker/docker"
  revision = "a422774e593b33bd287d9890544ad9e09b380d8c"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.1.1"

[[constraint]]
  name = "github.com/evalphobia/logrus_sentry"
  version = "~0.4.6"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "~1.1.0"

[[constraint]]
  name = "github.com/olebedev/config"
  revision = "dd1049a3738432dfc49417e2ae5bd97e132ecac6"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "~1.6.3"

[[constraint]]
  name = "github.com/influxdata/telegraf"
  version = "~1.8.2"

[prune]
  go-tests = true
  unused-packages = true
